package cn.jpush.android.ar;

import cn.jiguang.union.ads.api.JUnionAdError;

/* loaded from: classes.dex */
public class f extends JUnionAdError {
    static {
        JUnionAdError.map.put(1200, "in-app message not display background");
        JUnionAdError.map.put(1209, "in-app message build failed");
        JUnionAdError.map.put(1202, "in-app message count limit should not show");
        JUnionAdError.map.put(1203, "in-app message interval limit should not show");
        JUnionAdError.map.put(1204, "in-app message resource download failed, in app not display");
        JUnionAdError.map.put(1205, "in-app message json parse success");
        JUnionAdError.map.put(1206, "in-app message intercept by user");
        JUnionAdError.map.put(1210, "in-app message show success");
        JUnionAdError.map.put(1211, "in-app message show failed");
        JUnionAdError.map.put(1219, "in-app message click");
        JUnionAdError.map.put(1214, "in-app message deeplink jumped success");
        JUnionAdError.map.put(1215, "in-app message deeplink jump failed");
        JUnionAdError.map.put(1212, "in-app message open wechat mini program success");
        JUnionAdError.map.put(1213, "in-app message open wechat mini program failed");
        JUnionAdError.map.put(1216, "in-app message open target app not install");
        JUnionAdError.map.put(1217, "in-app message fail-deeplink jump success");
        JUnionAdError.map.put(1218, "in-app message fail-deeplink jump failed");
        JUnionAdError.map.put(1220, "in-app message wechat mini program param error ");
        JUnionAdError.map.put(1221, "in-app message WX app is not original or not installed");
        JUnionAdError.map.put(1222, "in-app message WX version too low to support mini");
        JUnionAdError.map.put(1223, "in-app message wechat appid not match");
        JUnionAdError.map.put(1224, "in-app message wechat sign not match ");
        JUnionAdError.map.put(1207, "in-app message target packagename is empty");
        JUnionAdError.map.put(1208, "in-app message deeplink not show");
        JUnionAdError.map.put(1225, "in-app message  deeplink show");
        JUnionAdError.map.put(1226, "in-app message unsupport message style");
        JUnionAdError.map.put(1227, "in-app message not show, because has same ssp notification");
        JUnionAdError.map.put(1228, "in-app message layout not exists");
        JUnionAdError.map.put(1201, "in-app message not display background during delay time");
        JUnionAdError.map.put(1229, "in-app message delay to show for background to foreground");
        JUnionAdError.map.put(1230, "in-app message show failed for other display now.");
        JUnionAdError.map.put(1231, "in-app message html template download failed.");
        JUnionAdError.map.put(1232, "in-app message template image resource download failed.");
        JUnionAdError.map.put(1233, "in-app message template cache failed.");
        JUnionAdError.map.put(1234, "in-app message of h5 report data");
        JUnionAdError.map.put(1235, "in-app message new one override old display");
        JUnionAdError.map.put(1236, "in-app message h5 template load data failed");
        JUnionAdError.map.put(1237, "in-app message package installed not display");
        JUnionAdError.map.put(1238, "in-app message not show for url is empty or not start with http");
        JUnionAdError.map.put(1239, "in-app message start apk download");
        JUnionAdError.map.put(1240, "in-app message cancel apk download by data network");
        JUnionAdError.map.put(1241, "in-app message user pause apk download");
        JUnionAdError.map.put(1242, "in-app message user resume apk download");
        JUnionAdError.map.put(1243, "in-app message user swipe notification to stop apk download");
        JUnionAdError.map.put(1244, "in-app message apk download failed");
        JUnionAdError.map.put(1245, "in-app message apk download success");
        JUnionAdError.map.put(1246, "in-app message apk install failed");
        JUnionAdError.map.put(1247, "in-app message apk install success");
        JUnionAdError.map.put(1248, "in-app message apk installed already not download");
        JUnionAdError.map.put(1249, "in-app message user click close button");
        JUnionAdError.map.put(1250, "in-app message click jump failed for parse param");
        JUnionAdError.map.put(1251, "in-app message user click cancel");
        JUnionAdError.map.put(1252, "in-app message click h5 web content");
        JUnionAdError.map.put(1253, "in-app message activity param is null");
        JUnionAdError.map.put(1254, "in-app message occur unknown error");
        JUnionAdError.map.put(1255, "in-app message start apk install");
        JUnionAdError.map.put(1256, "in-app message start download apk no common service");
        JUnionAdError.map.put(1257, "in-app message param is null");
        JUnionAdError.map.put(1258, "in-app message progress notification build failed");
        JUnionAdError.map.put(1259, "in-app message progress notification display failed");
        JUnionAdError.map.put(1260, "in-app message get apk size failed");
        JUnionAdError.map.put(1261, "in-app message get apk size success");
        JUnionAdError.map.put(1262, "in-app message js load callback timeout");
        JUnionAdError.map.put(1263, "in-app message start ipc");
        JUnionAdError.map.put(1264, "in-app message apk install use cache file");
        JUnionAdError.map.put(1265, "in-app message service stop process exit");
        JUnionAdError.map.put(1266, "in-app message use local to replace template img failed");
        JUnionAdError.map.put(1267, "in-app message for new user link show");
        JUnionAdError.map.put(1268, "in-app message handle message unknown error");
        JUnionAdError.map.put(1269, "in-app message check frequency error");
        JUnionAdError.map.put(1270, "in-app message handle message display error");
        JUnionAdError.map.put(1271, "in-app message h5 template load data success to display message");
        JUnionAdError.map.put(1272, "in-app message display failed with win manager build");
        JUnionAdError.map.put(1273, "in-app message h5 template cache success");
        JUnionAdError.map.put(1274, "in-app message start install by browser failed");
        JUnionAdError.map.put(1275, "in-app message start install by browser success");
        JUnionAdError.map.put(1276, "in-app message unsupported install type");
        JUnionAdError.map.put(1277, "in-app message apk install condition unsupported");
        JUnionAdError.map.put(1278, "in-app message apk install condition supported");
        JUnionAdError.map.put(1279, "in-app message parse json failed");
        JUnionAdError.map.put(1280, "in-app message FileProvider or jpush_file_paths.xml not config");
        JUnionAdError.map.put(1281, "in-app message not config REQUEST_INSTALL_PACKAGES permission");
        JUnionAdError.map.put(1282, "in-app message receive message appId not match app package name");
        JUnionAdError.map.put(1283, "in-app message use local cache template resource");
        JUnionAdError.map.put(1284, "in-app message build webview failed");
        JUnionAdError.map.put(1285, "in-app message not permission of allowing unknown source app install");
        JUnionAdError.map.put(1286, "in-app message has permission of allowing unknown source app install");
        JUnionAdError.map.put(1287, "in-app message start apk download no network, add wait download task");
        JUnionAdError.map.put(1288, "in-app message install apk allow pop win to grant unknown source app install permission");
        JUnionAdError.map.put(1289, "in-app message no deeplink intent error, message not display");
        JUnionAdError.map.put(1290, "in-app message top activity not in main process, message not display");
        JUnionAdError.map.put(1291, "in-app message apk download path is null");
        JUnionAdError.map.put(1292, "in-app message build message failed-ex");
        JUnionAdError.map.put(1293, "in-app message jump failed for deeplink is null");
        JUnionAdError.map.put(1294, "in-app deeplink jump exception error");
        JUnionAdError.map.put(1295, "in-app message display by system alert");
        JUnionAdError.map.put(1296, "in-app message display failed by webview is null");
        JUnionAdError.map.put(1297, "in-app message display failed by win-manager is null");
        JUnionAdError.map.put(1298, "in-app message display failed by param is null");
        JUnionAdError.map.put(1299, "in-app message fail for new user link jumped");
        JUnionAdError.map.put(1300, "in-app message success for new user link jumped");
        JUnionAdError.map.put(1301, "in-app message not use fail url, fail action not 1");
        JUnionAdError.map.put(1302, "in-app message click not found action key");
        JUnionAdError.map.put(1303, "in-app message h5 template load image error(or timeout)");
        JUnionAdError.map.put(1304, "in-app message no wx intent error");
        JUnionAdError.map.put(1305, "in-app message wx origin id is empty");
        JUnionAdError.map.put(1306, "in-app message wx deeplink param error");
        JUnionAdError.map.put(1307, "in-app message parse wx param error");
        JUnionAdError.map.put(1308, "in-app message build download notification icon failed");
        JUnionAdError.map.put(1309, "in-app message recv duplicated message");
        JUnionAdError.map.put(1310, "in-app message is cached for notify in app displayed now");
        JUnionAdError.map.put(1311, "in-app message h5 activity on create");
        JUnionAdError.map.put(1312, "in-app message webview load h5 page started");
        JUnionAdError.map.put(1313, "in-app message h5 activity on destroy");
        JUnionAdError.map.put(1314, "in-app message h5 load error occur");
        JUnionAdError.map.put(1315, "in-app message dismiss manu slide");
        JUnionAdError.map.put(1316, "in-app message dismiss auto slide");
        JUnionAdError.map.put(1317, "in-app message dismiss on destroy");
        JUnionAdError.map.put(1318, "in-app message dismiss back to background");
        JUnionAdError.map.put(1319, "in-app message activity on paused");
        JUnionAdError.map.put(1320, "in-app message app back to background");
        JUnionAdError.map.put(1321, "in-app message app activity on resume");
        JUnionAdError.map.put(1322, "in-app message stop display to black page");
        JUnionAdError.map.put(1323, "in-app message expose end by process end");
        JUnionAdError.map.put(1324, "in-app message not display in black page");
        JUnionAdError.map.put(1325, "in-app message not request in black page");
        JUnionAdError.map.put(1326, "in-app h5 orientation and current orientation no same");
        JUnionAdError.map.put(1327, "in-app hb period set enable/disenable by user");
        JUnionAdError.map.put(1329, "in-app not display for not in srv specified page");
        JUnionAdError.map.put(1330, "in-app not display for entering the page that srv not specified");
        JUnionAdError.map.put(1331, "in-app not display for new user in google play");
        JUnionAdError.map.put(1332, "in-app not display for touching ad pos count limit");
        JUnionAdError.map.put(1334, "in-app override delay message");
        JUnionAdError.map.put(1336, "in-app exposure total time");
        JUnionAdError.map.put(1337, "in-app swipe dismiss click");
        JUnionAdError.map.put(1338, "in-app drop for exists already");
        JUnionAdError.map.put(1339, "in-app display success");
        JUnionAdError.map.put(1440, "in-app add view layout param is null");
        JUnionAdError.map.put(1441, "in-app display fail for catch error");
        JUnionAdError.map.put(1442, "in-app display fail for add view catch error");
        JUnionAdError.map.put(1443, "in-app drop delay ad message for page pause");
    }

    public f() {
        super(0);
    }
}
